Repository codervivek5/DORA-AI-Powered-Virtual-Personal-Assistant, pull requests merged in 2025-08, with the labels that each got.

#9 Initial Frontend Setup with Next.js & ShadCN UI (#1)
  frontend/.gitignore
  frontend/README.md
  frontend/components.json
  frontend/eslint.config.mjs
  frontend/jsconfig.json
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/favicon/android-chrome-192x192.png
  frontend/public/favicon/android-chrome-512x512.png
  frontend/public/favicon/apple-touch-icon.png
  frontend/public/favicon/favicon-16x16.png
  frontend/public/favicon/favicon-32x32.png
  frontend/public/favicon/favicon.ico
  frontend/public/favicon/site.webmanifest
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/(pages)/page.js
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.js
  frontend/src/components/ui/button.jsx
  frontend/src/lib/utils.js
Labels: good first issue, gssoc2025, level3, setup

#15 Revamped UI: Added gradient background, modular components, theme mod.
  .gitignore
  .vscode/settings.json
  backend/README.md
  backend/__pycache__/main.cpython-312.pyc
  backend/main.py
  backend/requirements.txt
  frontend/ACCESSIBILITY_REFACTOR_SUMMARY.md
  frontend/COMPONENT_DEMO_EXAMPLE.jsx
  frontend/COMPONENT_REFACTOR_README.md
  frontend/GRADIENT_THEME_IMPLEMENTATION.md
  frontend/ISSUES_FIXED_SUMMARY.md
  frontend/REFACTOR_SUMMARY.md
  frontend/THEME_TOGGLE_REMOVAL.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/background-gradient.jpg
  frontend/src/app/(pages)/page.js
  frontend/src/app/layout.js
  frontend/src/components/AccessibilityTester.jsx
  frontend/src/components/ChatBubble.jsx
  frontend/src/components/ChatWindow.jsx
  frontend/src/components/Demo.jsx
  frontend/src/components/LoadingIndicator.jsx
  frontend/src/components/MessageList.jsx
  frontend/src/components/ThemeProvider.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/components/UserInput.jsx
  frontend/src/components/VoiceToggleButton.jsx
  frontend/src/styles/background.css
  frontend/src/utils/accessibility.js
  frontend/tsconfig.json
Labels: good first issue, gssoc2025, level3

#14 Fixed Content table Issue#12
  README.md
Labels: good first issue, gssoc2025, level1

#16 Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: good first issue, gssoc2025, level1

#19 Fix the workflow for auto comment
  .github/workflows/greetings.yml
  .github/workflows/issue-create-automate-message.yml
  .github/workflows/main.yml
  .github/workflows/pr_create_automate-message.yml
Labels: good first issue, gssoc2025, level1
